[package]
name = "erc20_token"
version = "0.1.0"
authors = ["Parity Technologies <admin@parity.io>"]
edition = "2018"

[dependencies]
pdsl_core = { path = "../../../core" }
parity-codec = { version = "3.0", default-features = false, features = ["derive"] }

[lib]
name = "erc20_token"
crate-type = ["cdylib"]

[features]
default = []
test-env = ["pdsl_core/test-env"]

[profile.release]
panic = "abort"
lto = true
opt-level = "z"
