[package]
name = "subpeep"
version = "0.1.0"
authors = ["Robin Freyler <robin@parity.io>", "Parity Technologies <admin@parity.io>"]
edition = "2018"

[dependencies]
pdsl_core = { path = "../../pdsl_core" }

lazy_static = { version = "1.2", features = ["spin_no_std"] }
spin = { version = "0.4", default-features = false }

[dependencies.parity-codec]
version = "2.0"
default-features = false
features = ["derive", "full"]
git = "https://github.com/paritytech/parity-codec"
branch = "no_std_impls"

[lib]
name = "subpeep"
crate-type = ["cdylib"]

[features]
default = []
test-env = ["pdsl_core/test-env"]

[profile.release]
panic = "abort"
lto = true
