[package]
name = "erc20_token"
version = "0.1.0"
authors = ["Parity Technologies <admin@parity.io>"]
edition = "2018"

[dependencies]
pdsl_core = { path = "../../pdsl_core" }
parity-codec = { version = "2.2", default-features = false, features = ["derive"] }

lazy_static = { version = "1.2", features = ["spin_no_std"] }
spin = { version = "0.4", default-features = false }

[lib]
name = "erc20_token"
crate-type = ["cdylib"]

[features]
default = []
test-env = ["pdsl_core/test-env"]

[profile.release]
panic = "abort"
lto = true
