[package]
name = "fleet-inc"
version = "0.1.0"
authors = ["Parity Technologies <admin@parity.io>"]
edition = "2018"

[dependencies]
pdsl_core = { path = "../../core" }
pdsl_model = { path = "../../model" }
parity-codec = { version = "2.2", default-features = false, features = ["derive"] }

[lib]
name = "fleet_inc"
crate-type = ["cdylib"]

[features]
default = []
test-env = [
	"pdsl_core/test-env",
	"pdsl_model/test-env",
]

[profile.release]
panic = "abort"
lto = true
opt-level = "z"
